import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./common-components/Footer";
import Header from "./common-components/Header";
import { Toaster } from "react-hot-toast";
import { ProductProvider } from "./context/ProductProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProductProvider>
          <Toaster />
          <Header />
          <main className="text-font-primary min-h-[calc(100vh-184px)] container px-5 py-8 lg:py-12 mx-auto">
            {children}
          </main>
          <Footer />
        </ProductProvider>
      </body>
    </html>
  );
}
